### PR TITLE
Add Python-based, simple VISR method

### PR DESCRIPTION
**Pull request by tobiscode**
See https://github.com/kmaterna/Strain_2D/issues/40.

Also changes a non-cyclic colormap to a cyclic one for the azimuth, and updates the blue/red colormap taken from Matlab which is deprecated (feel free to not merge this change if there's a different colormap preference).

This version produces the [rad/Ga] output as every other method does, so that would still need to be addressed alongside the other methods (see https://github.com/kmaterna/Strain_2D/issues/43)

Example output: 
grafik

### CODE REVIEW

**Comment by tobiscode** [comment]
Alright @kmaterna and @jlmaurer , I believe this is now a version you could try for yourself, if you're still interested in integrating it into your toolkit. Heads-up this method is much slower than the others, so maybe try it with a coarse grid in the beginning. Let me know if you have any questions!

**Comment by jlmaurer** [comment]
Fantastic @tobiscode! I'll check it out and ask my student if she can benchmark it against her visr code. Thanks for your effort!

**Comment by kmaterna** [comment]
@tobiscode this works great on my machine.  I reproduced the figures from your screen shot - it looks very physically reasonable.  I can do a quantitative comparison with VISR but at a later time. 
The sign of the rotation is backwards from the other methods now that the abs() is gone.  Perhaps it would be simplest for you to push another commit with the negative sign?  Thank you!

**Comment by tobiscode** [comment]
Thanks for checking out the code! I now use the other rotation matrix component so the sign should be correct now. Let me know if there's anything else you'd like improved.

Cheers

**Comment by kmaterna** [comment]
Works great now.  merging!

**Pull request merged**
