### PR TITLE
New methods, better descriptions

### LINKED ISSUE #10: VELMAP-style strain rate method?
VELMAP is a (non-open-source) code for computing strain rates from GNSS and InSAR. Original reference is [Wang & Wright, 2012](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2012GL051222), but used more recently by [Weiss et al. (2020)](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020GL087376). The methodology is pretty simple, basically the following: 
- Divide the region into cells (Wang & Wright use triangular cells) and assume the velocity only varies linearly with position inside each cell. 
- Define interpolation kernels for GPS, InSAR, whatever other datasets you have. 
- If both InSAR and GPS, define the kernel for removing a bi-linear plane from the InSAR to match the GPS
- impose Laplacian smoothing on the interpolated field
- Solve for the velocities in the cells using least-squares that best match the observations 

Should we implement this method and add it, or simply add it to the list of non-implemented methods?

### PR DESCRIPTION
**Pull request by jlmaurer**
Starting a draft PR with new methods and bettter descriptions. 
1. Placeholder for adding a Haines and Holt method
2. Possibly a placeholder for adding a VELMAP-like method
3. Updating geostats descriptions and hopefully improving the method using Bayes' Theorem

Fixes #10

### CODE REVIEW

**Comment by jlmaurer** [comment]
@kmaterna I'm getting a funny error related to the I2 calculation when running delaunay (see the tutorial notebook in this PR). Any ideas on whats going on with that?

**Comment by kmaterna** [comment]
Ah, working on it.    Right away I can see that the last of my commits in the branch you're working shows me un-commenting one of the output lines that is probably causing the error.   
It think it's a stupid bug.  I wrote a single function meant to perform operations on 2D arrays, 1D arrays, and scalars, but probably didn't fully test it.  I'll let you know when it's fixed.

**Comment by kmaterna** [comment]
@jlmaurer fixed with two commits just now.  Found three simple typos that had just clearly never been on a testing path (e.g., ```e2``` instead of ```e2[i]```, and ```map_sacle``` instead of ```map_scale```).  Pushed two commits to my main branch if that's okay.

**Comment by jlmaurer** [comment]
@kmaterna I added some todos to this, mainly because I wanted to very quickly see the weighted residual misfit norm, and seems like that's hard to do at the moment. I also updated the tutorial; I would like to add running a couple more methods and then the comparison script, but wanted to get some of the other issues out there first.

**Comment by kmaterna** [comment]
@jlmaurer I'll check this out soon when I get a chance and merge.  Btw back on main, I added the misfit when write_metrics == 1 (both printed and written), and it was a beautiful idea.

**Pull request merged**
